### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nicothin** [epixx/start-kit#1]
- [x] Добавить генератор папки блока и его файлов с дописыванием импорта блока в `style.scss`
- [x] Убить `src/_include`, запилить файлы шаблонов для pug
- [x] Добавить бьютификацию разметки, получаемой из pug

**Comment by Gurylev** [comment]
На счёт бьютификации вёрстки я юзаю и рекомендую это
```
.pipe(require('gulp-html-prettify')({
	indent_char: ' ',
	indent_size: 2
}))
```
